---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: master
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
