pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test --no-build tests/AgDatabaseMove.Unit --logger="trx;LogFileName=../../TestResults/AgDatabaseMove.Unit/results.trx" --configuration $(buildConfiguration)
- powershell: |
    dotnet add ./src/AgDatabaseMove.csproj package JetBrains.ReSharper.CommandLineTools --package-directory ./tools
    Get-ChildItem -Recurse -Path './*/cleanupcode.exe' | ForEach { &$_.Fullname /config="cleanupcode.config" }
    git diff --quiet --ignore-cr-at-eol
  displayName: ReSharper Code Cleanup
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: XUnit
    testResultsFiles: '**/*.trx'