version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    steps:
      - checkout
      - run: dotnet build /property:OutDir=bin\Release\ /p:Configuration=Release AgDatabaseMove.sln
      - run: dotnet test --no-build tests/AgDatabaseMove.Unit
      - run: find .
      - store_artifacts:
        path: /bin/release