version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    steps:
      - checkout
      - run: dotnet build -c Debug AgDatabaseMove.sln
      - run: dotnet build -c Release AgDatabaseMove.sln
      - run: dotnet test --no-build tests/AgDatabaseMove.Unit
      - run: find .
      - store_artifacts:
          path: src/bin/Release/netstandard2.0