version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    steps:
      - checkout
      - run: dotnet build -c Debug AgDatabaseMove.sln
      - run: dotnet build -c Release AgDatabaseMove.sln
      - run: dotnet test --no-build tests/AgDatabaseMove.Unit --logger="trx;LogFileName=../../TestResults/AgDatabaseMove.Unit/results.trx"
      - run: dotnet tool install -g trx2junit
      - run: find /root/.dotnet/tools
      - run: export PATH="$PATH:/root/.dotnet/tools"
      - run: dotnet trx2junit tests/testresults/agdatabasemove.unit/results.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: src/bin/Release/netstandard2.0
      - store_artifacts:
          path: tests/TestResults