version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    steps:
      - checkout
      - run: find .
      - run: dotnet build AgDatabaseMove.sln
      - run: dotnet test --no-build tests/AgDatabaseMove.Unit